name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Reuse steps from Pull Request workflow
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm -r --frozen-lockfile install

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
